accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),

    path("create/", AccountCreateView.as_view(), name="create"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path("detail/<int:pk>/", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", AccountDeleteView.as_view(), name="delete"),



]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView

app_name = 'articleapp'

urlpatterns = [

    path('temp/', TempView.as_view(), name="temp"),
    path('create/', ArticleCreateView.as_view(), name="create"),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name="detail"),


]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

techit230831/urls.py
from django.conf import settings
from django.conf.global_settings import MEDIA_URL
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.

class Registration(models.Model):
    email = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    image = models.ImageField(upload_to='article/', null=False)
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True)

    like = models.IntegerField(default=0)

    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    nickname = models.CharField(max_length=50, null=False, unique=True)
    image = models.ImageField(upload_to="profile/", null=True)
    message = models.CharField(max_length=100, null=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

accountapp/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = [
            'image',
            'title',
            'content',
        ]

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import Registration


# Create your views here.

def hello_world(request):
    if request.method == "POST":
        email = request.POST.get('email')

        reg = Registration()
        reg.email = email
        reg.save()

        reg_all = Registration.objects.all()



        return HttpResponseRedirect(reverse("accountapp:hello_world"))

    reg_all = Registration.objects.all()


    temp = "techit"
    return render(request, "accountapp/hello_world.html",
                  context={"temp": temp,
                           "reg_all": reg_all})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/create.html"

class AccountLoginView(LoginView):
    template_name = "accountapp/login.html"

class AccountLogoutView(LogoutView):
    pass

class AccountDetailView(DetailView):
    model = User
    template_name = "accountapp/detail.html"
    context_object_name = "target_user"

@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = "target_user"
    template_name = "accountapp/update.html"

    def get_success_url(self):
        return reverse("accountapp:detail",
                       kwargs = {"pk":self.kwargs["pk"]})


@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = "accountapp/delete.html"

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, CreateView, DetailView

from articleapp.forms import ArticleForm
from articleapp.models import Article


# Create your views here.

class TempView(TemplateView):
    template_name = 'articleapp/temp.html'

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articleapp/create.html'

    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'tqrget_article'
    template_name = 'articleapp/detail.html'

profileapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


# Create your views here.

class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      SignUp
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Quit : {{ target_user.username }}
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-danger rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  {% if target_user.profile %}
  <img src="{{ target_user.profile.image.url }}" alt=""
       style="height: 15rem; width: 15rem; border-radius: 10rem; margin-bottom: 2rem;">
  <div class="my-3">
    <h1>
      {{ target_user.profile.nickname }}
        {% if target_user == user %}
      <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
        edit
      </a>
        {% endif %}
    </h1>
  </div>
  <h5 style="margin-bottom: 3rem">
    {{ target_user.profile.message }}
  </h5>
  {% else %}
  {% if target_user == user %}
  <a href="{% url 'profileapp:create' %}">
    <h1>
      Create Profile
    </h1>
  </a>
    {% else %}
    <h2>
      닉네임 미설정
    </h2>
    {% endif %}
  {% endif %}


  <div style="max-width: 900px; margin: auto">
    {{ target_user.date_joined }}

    {% if user == target_user %}

    <div>
      <a href="{% url 'accountapp:update' pk=target_user.pk %}">
      <div class="btn btn-warning rounded-pill px-5 my-5">
      Update
      </div>
      </a>
    </div>

    {% endif %}
  </div>

</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}


<div style="text-align: center">


    <h2>
        Registration
    </h2>
    
    <div class="my-4">
        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}

            <div class="row g-2" style="max-width: 500px; margin: auto;">
                 <div class="col-md flex">
                    <div class="form-floating inline-block">
                         <input type="email" name="email" class="form-control" id="floatingInputGrid" placeholder="name@example.com" value="mdo@example.com">
                         <label for="floatingInputGrid">Email address</label>
                    </div>
                     <button type="submit" class="btn btn-primary my-5 inline-block" type="submit" value="Submit">
                Submit
            </button>
                 </div>
            </div>


        </form>
    </div>

    <div>
        {{ temp }}
    </div>

    <div>
        {% for reg in reg_all %}

        <p>
            {{ reg.email }}
        </p>

        {% endfor %}
    </div>

</div>



{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Login
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'accountapp:login' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Account Info Update
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Article Create
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'articleapp:create' %}"
          method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      {{ target_article.title }}
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    
      <div>
          <img src="{{ target_article.image.url }}" alt="">
      </div>
      
      <div>
          {{ target_article.content }}
      </div>
      
  </div>

</div>

{% endblock %}

articleapp/templates/articleapp/temp.html
{% extends 'base.html' %}

{% block content %}


<style>
  .container div {
    width: 280px;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 8px;
  }

  .container img {

   width: 100%;
   border-radius: 2rem;


  }

</style>

<div>
  <div class="container">
    <div class="item1">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
    <div class="item2">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
    <div class="item3">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
    <div class="item4">
        <img src="https://picsum.photos/200/190" alt="">
    </div>
    <div class="item5">
        <img src="https://picsum.photos/200/210" alt="">
    </div>
    <div class="item6">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
    <div class="item7">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
    <div class="item8">
        <img src="https://picsum.photos/200/300" alt="">
    </div>
</div>

<script src="https://unpkg.com/magic-grid/dist/magic-grid.cjs.js"></script>
<script>
  let magicGrid = new MagicGrid({
    container: '.container',
    animate: true,
    gutter: 30,
    static: true,
    useMin: true
  });

  magicGrid.listen();

  var masonrys = document.getElementsByTagName("img")

  for (let i = 0; i < masonrys.length; i++) {
  masonrys[i].addEventListener('load', function () {
    magicGrid.positionItems();
  }, false)
  }
</script>

{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Profile Create
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

  <div>
    <h1>
      Update Profile
    </h1>
  </div>

  <div style="max-width: 900px; margin: auto">
    <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-warning rounded-pill px-4 my-5"
              type="submit">
        Submit
      </button>
    </form>
  </div>

</div>

{% endblock %}